name: Package Request
description: Request the addition of a new package to the project.
title: "Package Request: <Package Name>"
labels: ["package request"]

body:
  - type: markdown
    attributes:
      value: >
        This is a form to request adding a new package.
        
  - type: input
    id: package_name
    attributes:
      label: Package Name
      description: Please enter the name of the package you are requesting to add. Only one package can be entered. If multiple packages are needed, please create a separate issue for each package.
      placeholder: "pandas"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: (Optional) Version
      description:  Please specify if a particular version is required.
      placeholder: "1.5.0"
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: Please confirm and check all the following items.
      options:
        - label: I confirmed that the package name is correct.
          required: true
        - label: I entered only one package name.
          required: true
        - label: I specified if a particular version is required. (If no version is specified, the latest version will be applied.)
          required: true
